#!/bin/bash

#dmesg -c > /dev/null
echo "Loading configurations"
source config

# Print out configurations
__RED='\033[0;31m'
__NC='\033[0m' # No Color

echo -e "${__RED}====================="

echo "Number of jobs: "$njob
echo "Number of rows per job: "$nrows
echo "Record size: "$datasize
echo "Sync mode: "$syncmode

echo -e "=====================${__NC}"


# Start to test
echo "Test start"

if [ $SQLEngine == Shell ]; then
	source tools/useShell
elif [ $SQLEngine == C ]; then
	source tools/useC
else
	echo "Not supported SQL engine:"$SQLEngine
	exit
fi

echo "Collecting results"
./tools/collectResult

